// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcodoeqjlgmpxwajseoe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jb2RvZXFqbGdtcHh3YWpzZW9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NTEwMDUsImV4cCI6MjA3MDEyNzAwNX0.rl3C508pF1YuPjwJPAQ7runvt2aB9ws2n-rlQMMZqug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});